spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:~/nisum-reto-tecnico
    password: ''
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
        trace: false
      path: /h2-console
      allowed-origins: "*"
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  sql:
    init:
      platform: h2

server:
  port: 8082
  servlet:
    context-path: /nisum-reto-tecnico
