spring:

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:~/nisum-reto-tecnico
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  sql:
    init:
      data-locations: classpath:script.sql
server:
  port: 8082
  servlet:
    context-path: /nisum-reto-tecnico
